/* Preserve dnd_tracker_audio v1 / tracks / ids / blobs and existing settings. */
(()=>{'use strict';
const key='dnd_audio_settings_v1',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let prefs;try{prefs=JSON.parse(localStorage.getItem(key)||'{}');}catch{prefs={};}prefs={musicVolume:.5,soundVolume:.7,repeat:false,soundRepeat:false,folders:['Общее'],gains:{},loops:{},...prefs};prefs.gains||={};prefs.loops||={};
let db,rows=[],kind='music',folder='',query='',editing=null;const selected={music:null,sound:null};
const shell=document.createElement('section');shell.className='tracker-audio';shell.innerHTML=`<button class="audio-orb" aria-label="Открыть плеер" title="Музыка и звуки">♫</button><div class="audio-panel" hidden><header class="audio-drag"><div><small>АТМОСФЕРА СЕССИИ</small><strong>Звуки приключения</strong></div><button class="audio-close" aria-label="Закрыть плеер">×</button></header><nav><button data-kind="music">♫ Музыка</button><button data-kind="sound">✦ Звуки</button></nav><div class="audio-library-tools"><input class="audio-search" placeholder="Найти композицию или звук…" aria-label="Поиск аудио"><select class="audio-folder" aria-label="Папка"></select><button class="audio-new-folder" title="Создать папку">＋</button></div><form class="audio-folder-form" hidden><input aria-label="Название папки" placeholder="Название папки" maxlength="60" required><button>Создать</button></form><label class="audio-upload">＋ Добавить файлы<input type="file" accept="audio/*,.mp3,.ogg,.wav,.m4a,.flac" multiple hidden></label><p class="audio-status" role="status">Один музыкальный трек и несколько звуков одновременно.</p><div class="audio-tracks"></div><section class="audio-layers"><div class="audio-section-label">В миксе <button class="audio-stop-all" title="Остановить всё">Остановить всё</button></div><div class="audio-active"></div></section><footer><div class="audio-now">Выбери трек или звук</div><div class="audio-seek-wrap"><input class="audio-seek" type="range" min="0" max="100" step=".1" value="0" aria-label="Позиция воспроизведения"><output class="audio-time-preview" hidden></output></div><div class="audio-time">0:00 / 0:00</div><div class="audio-transport"><button class="audio-prev" aria-label="Предыдущий файл">⏮</button><button class="audio-play" aria-label="Воспроизведение или пауза">▶</button><button class="audio-next" aria-label="Следующий файл">⏭</button><button class="audio-stop" aria-label="Остановить выбранный файл">■</button><button class="audio-repeat" aria-label="Повтор выбранного файла">↻</button></div><label class="audio-gain-row">Этот файл<input class="audio-gain" type="range" min="0" max="1" step=".01" value="1"><output>100%</output></label><div class="audio-master-volumes"><label>Музыка<input class="audio-volume" data-channel="music" type="range" min="0" max="1" step=".01" value="${prefs.musicVolume}"><output></output></label><label>Звуки<input class="audio-volume" data-channel="sound" type="range" min="0" max="1" step=".01" value="${prefs.soundVolume}"><output></output></label></div></footer></div>`;document.body.append(shell);
const $=s=>shell.querySelector(s),panel=$('.audio-panel'),status=$('.audio-status'),time=n=>{n=Number.isFinite(n)?Math.max(0,Math.floor(n)):0;return Math.floor(n/60)+':'+String(n%60).padStart(2,'0');};
const mixer=new AudioMixer({singleMusic:true,volume:k=>Number(prefs[k+'Volume']),gain:id=>prefs.gains[id]??1,loop:r=>prefs.loops[r.id]??(r.kind==='music'?prefs.repeat:prefs.soundRepeat),onChange:error=>{if(error)status.textContent=error.message;refreshPlayback();},onTick:e=>{if(e.id===selected[kind])refreshTimeline();},onEnded:e=>{if(e.kind==='music'&&selected.music===e.id&&!e.audio.loop)step(1,'music');}});
function save(){try{localStorage.setItem(key,JSON.stringify(prefs));}catch{status.textContent='Не удалось сохранить настройки плеера.';}}
function transaction(mode,fn){return new Promise((resolve,reject)=>{const t=db.transaction('tracks',mode);let result;try{result=fn(t.objectStore('tracks'));}catch(e){reject(e);return;}t.oncomplete=()=>resolve(result?.result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Сохранение отменено'));});}
async function load(){rows=await transaction('readonly',s=>s.getAll());render();}
const filtered=(channel=kind)=>rows.filter(r=>r.kind===channel&&(query.trim()||!folder||r.folder===folder)&&r.name.toLocaleLowerCase().includes(query));
function render(){const folders=[...new Set([...prefs.folders,...rows.map(r=>r.folder)])];$('.audio-folder').innerHTML='<option value="">Все папки</option>'+folders.map(f=>`<option ${folder===f?'selected':''}>${esc(f)}</option>`).join('');shell.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===kind)));$('.audio-tracks').innerHTML=filtered().map(r=>`<div class="audio-track" data-track="${r.id}"><button data-play="${r.id}" aria-label="Воспроизведение или пауза: ${esc(r.name)}">▶</button><button class="audio-track-name" data-select="${r.id}" title="Выбрать для перемотки и настройки"><span>${esc(r.name)}</span><small>${esc(r.folder)}</small></button><button data-rename="${r.id}" aria-label="Переименовать ${esc(r.name)}" title="Переименовать">✎</button><details class="audio-track-menu"><summary aria-label="Действия с ${esc(r.name)}">⋯</summary><div><select data-move="${r.id}" aria-label="Папка для ${esc(r.name)}">${folders.map(f=>`<option ${r.folder===f?'selected':''}>${esc(f)}</option>`).join('')}</select><button data-delete="${r.id}">Удалить файл</button></div></details>${editing===r.id?`<form class="audio-rename-form" data-edit="${r.id}"><input aria-label="Новое название" value="${esc(r.name)}" maxlength="200" required><button>Сохранить</button><button type="button" data-cancel-rename>×</button></form>`:''}</div>`).join('')||'<div class="audio-empty">Ничего не найдено · добавь файлы или измени поиск</div>';refreshPlayback();fitPanel();}
function select(id){const r=rows.find(r=>r.id===id);if(!r)return;kind=r.kind;selected[kind]=id;refreshPlayback();}
async function play(id){const r=rows.find(r=>r.id===id);if(!r)return;selected[r.kind]=id;try{await mixer.toggle(r);status.textContent='Музыка играет по одному треку, звуки можно сочетать.';}catch{status.textContent='Файл не поддерживается браузером или воспроизведение заблокировано.';}refreshPlayback();}
function step(direction,channel=kind){const list=filtered(channel);if(!list.length)return;const id=selected[channel];let i=list.findIndex(r=>r.id===id);if(i<0)i=direction>0?-1:0;const next=list[(i+direction+list.length)%list.length];if(next.id===id){const e=mixer.entries.get(id);if(e){e.audio.currentTime=0;if(e.audio.paused)play(id);}return;}mixer.remove(id);selected[channel]=next.id;const entry=mixer.entries.get(next.id);if(entry&&!entry.audio.paused){refreshPlayback();return;}play(next.id);}
function setRange(el,value){el.value=value;el.style.setProperty('--progress',(Number(value)/Number(el.max)*100)+'%');}
function refreshTimeline(){const a=mixer.entries.get(selected[kind])?.audio,duration=Number.isFinite(a?.duration)?a.duration:0;setRange($('.audio-seek'),duration?a.currentTime/duration*100:0);$('.audio-time').textContent=time(a?.currentTime)+' / '+time(duration);$('.audio-seek').disabled=!duration;}
function refreshPlayback(){const id=selected[kind],row=rows.find(r=>r.id===id),entry=mixer.entries.get(id);$('.audio-now').textContent=row?.name||'Выбери трек или звук';$('.audio-play').textContent=entry&&!entry.audio.paused?'Ⅱ':'▶';const loop=entry?.audio.loop??prefs.loops[id]??(kind==='music'?prefs.repeat:prefs.soundRepeat);$('.audio-repeat').setAttribute('aria-pressed',String(!!loop));const gain=prefs.gains[id]??1;setRange($('.audio-gain'),gain);$('.audio-gain').disabled=!row;$('.audio-gain-row output').textContent=Math.round(gain*100)+'%';for(const el of shell.querySelectorAll('[data-track]')){const item=mixer.entries.get(el.dataset.track),playing=item&&!item.audio.paused;el.classList.toggle('selected',el.dataset.track===id);el.classList.toggle('playing',!!playing);el.querySelector('[data-play]').textContent=playing?'Ⅱ':'▶';}$('.audio-active').innerHTML=[...mixer.entries.values()].filter(e=>!e.audio.ended).map(e=>`<span class="audio-layer ${e.id===id?'selected':''}"><button data-focus="${e.id}" title="Выбрать файл для управления">${e.audio.paused?'Ⅱ':'♫'} ${esc(rows.find(r=>r.id===e.id)?.name||'Файл')}</button><button data-remove-mix="${e.id}" aria-label="Убрать из микса: ${esc(rows.find(r=>r.id===e.id)?.name||'Файл')}" title="Убрать из микса">×</button></span>`).join('')||'<small>Добавь атмосферу и звуковые эффекты</small>';refreshTimeline();}
$('.audio-orb').onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden)fitPanel();};$('.audio-close').onclick=()=>panel.hidden=true;
shell.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;editing=null;render();});$('.audio-search').oninput=e=>{query=e.target.value.toLocaleLowerCase();render();};$('.audio-folder').onchange=e=>{folder=e.target.value;render();};$('.audio-new-folder').onclick=()=>{$('.audio-folder-form').hidden=!$('.audio-folder-form').hidden;fitPanel();};$('.audio-folder-form').onsubmit=e=>{e.preventDefault();const name=e.target.querySelector('input').value.trim();if(name&&!prefs.folders.includes(name)){prefs.folders.push(name);save();}folder=name;e.target.reset();e.target.hidden=true;render();};
$('.audio-upload input').onchange=async e=>{if(!db){status.textContent='Хранилище аудио недоступно.';return;}const files=[...e.target.files],destination=folder||'Общее',uploadKind=kind;try{for(const file of files){if(!file.type.startsWith('audio/')&&!/\.(mp3|ogg|wav|m4a|flac)$/i.test(file.name))continue;await transaction('readwrite',s=>s.add({id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),kind:uploadKind,folder:destination,blob:file}));}await load();status.textContent='Файлы добавлены. Существующая библиотека сохранена.';navigator.storage?.persist?.().catch(()=>{});}catch{await load();status.textContent='Не удалось сохранить все файлы: возможно, не хватает места.';}e.target.value='';};
$('.audio-tracks').onclick=async e=>{const p=e.target.closest('[data-play]'),s=e.target.closest('[data-select]'),rename=e.target.closest('[data-rename]'),d=e.target.closest('[data-delete]');if(p)play(p.dataset.play);if(s)select(s.dataset.select);if(rename){editing=rename.dataset.rename;render();$('.audio-rename-form input')?.focus();}if(e.target.closest('[data-cancel-rename]')){editing=null;render();}if(d){try{await transaction('readwrite',s=>s.delete(d.dataset.delete));mixer.remove(d.dataset.delete);for(const k of ['music','sound'])if(selected[k]===d.dataset.delete)selected[k]=null;await load();}catch{status.textContent='Не удалось удалить файл.';}}};
$('.audio-tracks').onsubmit=async e=>{const form=e.target.closest('[data-edit]');if(!form)return;e.preventDefault();const name=form.querySelector('input').value.trim();if(!name)return;try{const updated=await AudioLibrary.updateMetadata(db,form.dataset.edit,{name}),i=rows.findIndex(r=>r.id===updated.id);rows[i]=updated;if(editing===updated.id){editing=null;render();}else{const label=$('[data-track="'+updated.id+'"] .audio-track-name span');if(label)label.textContent=updated.name;refreshPlayback();}status.textContent='Название сохранено. Аудиофайл не изменён.';}catch{status.textContent='Не удалось сохранить название.';}};
$('.audio-tracks').onchange=async e=>{if(!e.target.dataset.move)return;try{const updated=await AudioLibrary.updateMetadata(db,e.target.dataset.move,{folder:e.target.value}),i=rows.findIndex(r=>r.id===updated.id);rows[i]=updated;render();}catch{status.textContent='Не удалось изменить папку.';}};
$('.audio-active').onclick=e=>{const remove=e.target.closest('[data-remove-mix]');if(remove){const id=remove.dataset.removeMix;for(const channel of ['music','sound'])if(selected[channel]===id)selected[channel]=null;mixer.remove(id);refreshPlayback();fitPanel();status.textContent='Файл убран из микса и сохранён в библиотеке.';return;}const b=e.target.closest('[data-focus]');if(b){select(b.dataset.focus);render();}};
$('.audio-play').onclick=()=>{const id=selected[kind];if(id)play(id);else step(1);};$('.audio-prev').onclick=()=>step(-1);$('.audio-next').onclick=()=>step(1);$('.audio-stop').onclick=()=>mixer.stop(selected[kind]);$('.audio-stop-all').onclick=()=>mixer.stopAll();$('.audio-repeat').onclick=()=>{const id=selected[kind],entry=mixer.entries.get(id),value=!(entry?.audio.loop??prefs.loops[id]??(kind==='music'?prefs.repeat:prefs.soundRepeat));if(id)prefs.loops[id]=value;else prefs[kind==='music'?'repeat':'soundRepeat']=value;if(entry)entry.audio.loop=value;save();refreshPlayback();};
for(const input of shell.querySelectorAll('.audio-volume')){const apply=()=>{const c=input.dataset.channel,value=Number(input.value);prefs[c+'Volume']=value;mixer.setVolume(c,value);setRange(input,value);input.parentElement.querySelector('output').textContent=Math.round(value*100)+'%';input.title=Math.round(value*100)+'%';};input.oninput=()=>{apply();save();};apply();}
$('.audio-gain').oninput=e=>{const id=selected[kind];if(!id)return;const value=Number(e.target.value);prefs.gains[id]=value;mixer.setGain(id,value);setRange(e.target,value);$('.audio-gain-row output').textContent=Math.round(value*100)+'%';save();};
$('.audio-seek').oninput=e=>{const a=mixer.entries.get(selected[kind])?.audio;if(Number.isFinite(a?.duration)){a.currentTime=a.duration*Number(e.target.value)/100;refreshTimeline();}};
$('.audio-seek').onpointermove=e=>{const a=mixer.entries.get(selected[kind])?.audio,el=e.currentTarget,preview=$('.audio-time-preview');if(!Number.isFinite(a?.duration)||!a.duration)return;const r=el.getBoundingClientRect(),part=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));preview.hidden=false;preview.textContent=time(a.duration*part);preview.style.left=Math.max(20,Math.min(r.width-20,part*r.width))+'px';el.title='Перейти к '+preview.textContent;};$('.audio-seek').onpointerleave=()=>$('.audio-time-preview').hidden=true;
function fitPanel(){if(panel.hidden)return;const r=shell.getBoundingClientRect(),w=Math.min(400,innerWidth-24),h=Math.min(panel.scrollHeight,innerHeight-86);panel.style.position='fixed';panel.style.right='auto';panel.style.bottom='auto';panel.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';panel.style.top=Math.max(12,Math.min(innerHeight-h-12,r.top>innerHeight/2?r.top-h-10:r.bottom+10))+'px';}
function place(x,y){x=Math.max(8,Math.min(innerWidth-64,x));y=Math.max(8,Math.min(innerHeight-64,y));shell.style.left=x+'px';shell.style.top=y+'px';shell.style.right='auto';shell.style.bottom='auto';shell.classList.toggle('audio-left',x<innerWidth/2);shell.classList.toggle('audio-top',y<innerHeight/2);prefs.position={x,y};fitPanel();}
if(prefs.position)place(prefs.position.x,prefs.position.y);let drag=null,moved=false;shell.addEventListener('pointerdown',e=>{if(!e.target.closest('.audio-orb,.audio-drag')||e.target.closest('.audio-close'))return;const rect=shell.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:rect.left,top:rect.top};moved=false;e.target.setPointerCapture(e.pointerId);});shell.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;if(moved)place(drag.left+dx,drag.top+dy);});shell.addEventListener('pointerup',()=>{if(drag&&moved){save();shell.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();},{capture:true,once:true});}drag=null;});shell.addEventListener('pointercancel',()=>drag=null);addEventListener('resize',()=>{if(prefs.position)place(prefs.position.x,prefs.position.y);fitPanel();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){panel.hidden=true;e.stopImmediatePropagation();}},{capture:true});
const request=indexedDB.open('dnd_tracker_audio',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('tracks'))request.result.createObjectStore('tracks',{keyPath:'id'});};request.onsuccess=async()=>{db=request.result;try{await load();}catch{status.textContent='Не удалось загрузить библиотеку аудио.';}};request.onerror=()=>status.textContent='Браузер не разрешил хранение аудио.';addEventListener('pagehide',()=>mixer.dispose());
})();
