/* Local audio library: blobs stay in IndexedDB, independent music and sound channels. */
(()=>{'use strict';
const key='dnd_audio_settings_v1',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let prefs;try{prefs=JSON.parse(localStorage.getItem(key)||'{}');}catch{prefs={};}
prefs={musicVolume:.5,soundVolume:.7,repeat:false,folders:['Общее'],...prefs};
let db,rows=[],kind='music',folder='',query='',selected=null,musicUrl=null,soundUrl=null;
const music=new Audio(),sound=new Audio();music.volume=prefs.musicVolume;sound.volume=prefs.soundVolume;music.loop=!!prefs.repeat;
const shell=document.createElement('section');shell.className='tracker-audio';shell.innerHTML=`<button class="audio-orb" aria-label="Открыть плеер" title="Музыка и звуки">♫</button><div class="audio-panel" hidden><header class="audio-drag"><strong>♫ Звуки приключения</strong><button class="audio-close" aria-label="Закрыть плеер">×</button></header><nav><button data-kind="music">Музыка</button><button data-kind="sound">Звуки</button></nav><div class="audio-library-tools"><input class="audio-search" placeholder="Поиск по названию" aria-label="Поиск аудио"><select class="audio-folder" aria-label="Папка"></select><button class="audio-new-folder" title="Создать папку">＋</button></div><form class="audio-folder-form" hidden><input aria-label="Название папки" placeholder="Название папки" maxlength="60" required><button>Создать</button></form><label class="audio-upload">＋ Загрузить аудио<input type="file" accept="audio/*,.mp3,.ogg,.wav,.m4a,.flac" multiple hidden></label><p class="audio-status" role="status">Файлы сохраняются на этом устройстве.</p><div class="audio-tracks"></div><footer><div class="audio-now">Ничего не выбрано</div><div class="audio-transport"><button class="audio-prev" aria-label="Предыдущая композиция">⏮</button><button class="audio-play" aria-label="Воспроизведение или пауза">▶</button><button class="audio-next" aria-label="Следующая композиция">⏭</button><button class="audio-stop" aria-label="Остановить музыку и звуки">■</button><button class="audio-repeat" aria-label="Повтор композиции" aria-pressed="${!!prefs.repeat}">↻</button></div><input class="audio-seek" type="range" min="0" max="100" value="0" aria-label="Позиция воспроизведения"><div class="audio-time">0:00 / 0:00</div><label>Музыка<input class="audio-volume" data-channel="music" type="range" min="0" max="1" step=".01" value="${prefs.musicVolume}"></label><label>Звуки<input class="audio-volume" data-channel="sound" type="range" min="0" max="1" step=".01" value="${prefs.soundVolume}"></label></footer></div>`;document.body.append(shell);
const $=s=>shell.querySelector(s),panel=$('.audio-panel'),status=$('.audio-status');
function save(){try{localStorage.setItem(key,JSON.stringify(prefs));}catch{status.textContent='Не удалось сохранить настройки плеера.';}}
function transaction(mode,fn){return new Promise((resolve,reject)=>{const t=db.transaction('tracks',mode);let result;try{result=fn(t.objectStore('tracks'));}catch(e){reject(e);return;}t.oncomplete=()=>resolve(result?.result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Сохранение отменено'));});}
async function load(){rows=await transaction('readonly',s=>s.getAll());render();}
function render(){const folders=[...new Set([...prefs.folders,...rows.map(r=>r.folder)])];$('.audio-folder').innerHTML='<option value="">Все папки</option>'+folders.map(f=>`<option ${folder===f?'selected':''}>${esc(f)}</option>`).join('');shell.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===kind)));const filtered=rows.filter(r=>r.kind===kind&&(!folder||r.folder===folder)&&r.name.toLocaleLowerCase().includes(query));$('.audio-tracks').innerHTML=filtered.map(r=>`<div class="audio-track ${selected===r.id?'selected':''}"><button data-play="${r.id}" title="Включить">${r.kind==='sound'?'✦':'♫'} <span>${esc(r.name)}<small>${esc(r.folder)}</small></span></button><select data-move="${r.id}" aria-label="Папка для ${esc(r.name)}">${folders.map(f=>`<option ${r.folder===f?'selected':''}>${esc(f)}</option>`).join('')}</select><button data-delete="${r.id}" aria-label="Удалить ${esc(r.name)}">×</button></div>`).join('')||'<div class="audio-empty">Загрузите файлы или измените фильтр</div>';}
async function play(id){const r=rows.find(r=>r.id===id);if(!r)return;const channel=r.kind==='sound'?sound:music;channel.pause();const old=r.kind==='sound'?soundUrl:musicUrl;if(old)URL.revokeObjectURL(old);const url=URL.createObjectURL(r.blob);if(r.kind==='sound')soundUrl=url;else{musicUrl=url;selected=id;$('.audio-now').textContent=r.name;}channel.src=url;try{await channel.play();status.textContent=r.kind==='sound'?'Звук: '+r.name:'Играет: '+r.name;}catch{status.textContent='Файл не поддерживается браузером или воспроизведение заблокировано.';}render();}
function step(direction){const list=rows.filter(r=>r.kind==='music'&&(!folder||r.folder===folder));if(!list.length)return;let i=list.findIndex(r=>r.id===selected);play(list[(i+direction+list.length)%list.length].id);}
$('.audio-orb').onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden)fitPanel();};$('.audio-close').onclick=()=>panel.hidden=true;
shell.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;render();});$('.audio-search').oninput=e=>{query=e.target.value.toLocaleLowerCase();render();};$('.audio-folder').onchange=e=>{folder=e.target.value;render();};$('.audio-new-folder').onclick=()=>{$('.audio-folder-form').hidden=!$('.audio-folder-form').hidden;};$('.audio-folder-form').onsubmit=e=>{e.preventDefault();const name=e.target.querySelector('input').value.trim();if(name&&!prefs.folders.includes(name)){prefs.folders.push(name);save();}folder=name;e.target.reset();e.target.hidden=true;render();};
$('.audio-upload input').onchange=async e=>{if(!db){status.textContent='Хранилище аудио недоступно.';return;}const files=[...e.target.files];const destination=folder||'Общее',uploadKind=kind;try{for(const file of files){if(!file.type.startsWith('audio/')&&!/\.(mp3|ogg|wav|m4a|flac)$/i.test(file.name))continue;await transaction('readwrite',s=>s.put({id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),kind:uploadKind,folder:destination,blob:file}));}await load();status.textContent='Аудио сохранено на этом устройстве.';navigator.storage?.persist?.().catch(()=>{});}catch{await load();status.textContent='Не удалось сохранить все файлы: возможно, не хватает места.';}e.target.value='';};
$('.audio-tracks').onclick=async e=>{const p=e.target.closest('[data-play]'),d=e.target.closest('[data-delete]');if(p)play(p.dataset.play);if(d){const id=d.dataset.delete;try{await transaction('readwrite',s=>s.delete(id));if(id===selected){music.pause();music.removeAttribute('src');music.load();selected=null;$('.audio-now').textContent='Ничего не выбрано';}await load();}catch{status.textContent='Не удалось удалить файл.';}}};$('.audio-tracks').onchange=async e=>{if(!e.target.dataset.move)return;const row=rows.find(r=>r.id===e.target.dataset.move);try{await transaction('readwrite',s=>s.put({...row,folder:e.target.value}));await load();}catch{status.textContent='Не удалось изменить папку.';}};
$('.audio-play').onclick=async()=>{if(!music.src){step(1);return;}if(music.paused){try{await music.play();}catch{status.textContent='Не удалось включить аудио.';}}else music.pause();};$('.audio-prev').onclick=()=>step(-1);$('.audio-next').onclick=()=>step(1);$('.audio-stop').onclick=()=>{for(const a of [music,sound]){a.pause();if(a.src)a.currentTime=0;}};$('.audio-repeat').onclick=e=>{prefs.repeat=!prefs.repeat;music.loop=prefs.repeat;e.currentTarget.setAttribute('aria-pressed',String(prefs.repeat));save();};shell.querySelectorAll('.audio-volume').forEach(input=>input.oninput=()=>{const c=input.dataset.channel;(c==='music'?music:sound).volume=Number(input.value);prefs[c+'Volume']=Number(input.value);save();});
const time=n=>{n=Number.isFinite(n)?Math.floor(n):0;return Math.floor(n/60)+':'+String(n%60).padStart(2,'0');};music.ontimeupdate=()=>{$('.audio-seek').value=music.duration?music.currentTime/music.duration*100:0;$('.audio-time').textContent=time(music.currentTime)+' / '+time(music.duration);};$('.audio-seek').oninput=e=>{if(Number.isFinite(music.duration))music.currentTime=music.duration*Number(e.target.value)/100;};music.onplay=()=>$('.audio-play').textContent='Ⅱ';music.onpause=()=>$('.audio-play').textContent='▶';music.onended=()=>{if(!music.loop)step(1);};for(const audio of [music,sound])audio.onerror=()=>status.textContent='Не удалось прочитать аудиофайл. Попробуйте MP3, OGG или WAV.';
function fitPanel(){if(panel.hidden)return;const r=shell.getBoundingClientRect(),w=Math.min(370,innerWidth-24),h=Math.min(panel.scrollHeight,innerHeight-86);panel.style.position='fixed';panel.style.right='auto';panel.style.bottom='auto';panel.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';panel.style.top=Math.max(12,Math.min(innerHeight-h-12,r.top>innerHeight/2?r.top-h-10:r.bottom+10))+'px';}
function place(x,y){x=Math.max(8,Math.min(innerWidth-64,x));y=Math.max(8,Math.min(innerHeight-64,y));shell.style.left=x+'px';shell.style.top=y+'px';shell.style.right='auto';shell.style.bottom='auto';shell.classList.toggle('audio-left',x<innerWidth/2);shell.classList.toggle('audio-top',y<innerHeight/2);prefs.position={x,y};fitPanel();}
if(prefs.position)place(prefs.position.x,prefs.position.y);let drag=null,moved=false;shell.addEventListener('pointerdown',e=>{if(!e.target.closest('.audio-orb,.audio-drag')||e.target.closest('.audio-close'))return;const rect=shell.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:rect.left,top:rect.top};moved=false;e.target.setPointerCapture(e.pointerId);});shell.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;if(moved)place(drag.left+dx,drag.top+dy);});shell.addEventListener('pointerup',()=>{if(drag&&moved){save();shell.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();},{capture:true,once:true});}drag=null;});shell.addEventListener('pointercancel',()=>drag=null);addEventListener('resize',()=>{if(prefs.position)place(prefs.position.x,prefs.position.y);fitPanel();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){panel.hidden=true;e.stopImmediatePropagation();}},{capture:true});
const request=indexedDB.open('dnd_tracker_audio',1);request.onupgradeneeded=()=>request.result.createObjectStore('tracks',{keyPath:'id'});request.onsuccess=async()=>{db=request.result;try{await load();}catch{status.textContent='Не удалось загрузить библиотеку аудио.';}};request.onerror=()=>status.textContent='Браузер не разрешил хранение аудио.';
})();
