/* Stored ZIP keeps audio binary: no base64 expansion and no library migration. */
(function(root){'use strict';
const enc=new TextEncoder(),dec=new TextDecoder(),table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
async function crc(blob){let value=0xffffffff;const reader=blob.stream().getReader();for(;;){const {value:chunk,done}=await reader.read();if(done)break;for(const byte of chunk)value=table[(value^byte)&255]^(value>>>8);}return (value^0xffffffff)>>>0;}
function header(size){const b=new Uint8Array(size);return {b,v:new DataView(b.buffer)};}
async function pack(files,progress=()=>{}){const parts=[],central=[];let offset=0,index=0;for(const [name,blob] of files){if(blob.size+offset>0xffffffff)throw Error('Архив превышает 4 ГБ.');progress(++index,files.length);const filename=enc.encode(name),sum=await crc(blob),h=header(30),c=header(46);h.v.setUint32(0,0x04034b50,true);h.v.setUint16(4,20,true);h.v.setUint16(6,0x800,true);h.v.setUint32(14,sum,true);h.v.setUint32(18,blob.size,true);h.v.setUint32(22,blob.size,true);h.v.setUint16(26,filename.length,true);parts.push(h.b,filename,blob);c.v.setUint32(0,0x02014b50,true);c.v.setUint16(4,20,true);c.v.setUint16(6,20,true);c.v.setUint16(8,0x800,true);c.v.setUint32(16,sum,true);c.v.setUint32(20,blob.size,true);c.v.setUint32(24,blob.size,true);c.v.setUint16(28,filename.length,true);c.v.setUint32(42,offset,true);central.push(c.b,filename);offset+=30+filename.length+blob.size;}if(files.length>65535)throw Error('Слишком много файлов.');const centralSize=central.reduce((n,p)=>n+p.length,0),end=header(22);end.v.setUint32(0,0x06054b50,true);end.v.setUint16(8,files.length,true);end.v.setUint16(10,files.length,true);end.v.setUint32(12,centralSize,true);end.v.setUint32(16,offset,true);return new Blob([...parts,...central,end.b],{type:'application/zip'});}
async function unpack(file){const files=new Map();let offset=0;while(offset+4<=file.size){const b=await file.slice(offset,offset+30).arrayBuffer(),v=new DataView(b);if(v.getUint32(0,true)!==0x04034b50)break;if(b.byteLength<30||v.getUint16(8,true)!==0||v.getUint16(6,true)&9)throw Error('Неподдерживаемый архив. Выберите ZIP, созданный трекером.');const size=v.getUint32(18,true),nameLength=v.getUint16(26,true),extra=v.getUint16(28,true),name=dec.decode(await file.slice(offset+30,offset+30+nameLength).arrayBuffer()),start=offset+30+nameLength+extra;if(start+size>file.size||files.has(name))throw Error('Архив повреждён.');const blob=file.slice(start,start+size);if(await crc(blob)!==v.getUint32(14,true))throw Error('Повреждён файл '+name);files.set(name,blob);offset=start+size;}return files;}
async function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('dnd_tracker_audio',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('tracks'))r.result.createObjectStore('tracks',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function all(db){return new Promise((resolve,reject)=>{const t=db.transaction('tracks','readonly'),r=t.objectStore('tracks').getAll();t.oncomplete=()=>resolve(r.result);t.onerror=()=>reject(t.error);});}
async function create(campaigns,progress){const db=await openDB();let tracks;try{tracks=await all(db);}finally{db.close();}const audio=tracks.map((r,i)=>{const {blob,...metadata}=r;return {...metadata,file:'audio/'+i+'.bin',mime:blob.type};}),manifest={format:'m4c9-full-backup',version:1,campaigns,audio,settings:{dnd_audio_settings_v1:localStorage.getItem('dnd_audio_settings_v1')}};const files=[['manifest.json',new Blob([JSON.stringify(manifest)],{type:'application/json'})],...tracks.map((r,i)=>['audio/'+i+'.bin',r.blob])];return {blob:await pack(files,progress),count:tracks.length};}
async function read(file){const files=await unpack(file);if(!files.has('manifest.json'))throw Error('В архиве нет данных трекера.');const m=JSON.parse(await files.get('manifest.json').text());if(m.format!=='m4c9-full-backup'||m.version!==1||!Array.isArray(m.audio))throw Error('Это не полная копия трекера.');TrackerBackup.validate(m.campaigns);if(m.settings?.dnd_audio_settings_v1!=null){const prefs=JSON.parse(m.settings.dnd_audio_settings_v1);if(!prefs||typeof prefs!=='object'||(prefs.folders!==undefined&&(!Array.isArray(prefs.folders)||prefs.folders.some(f=>typeof f!=='string'))))throw Error('Повреждены настройки аудио.');}const ids=new Set();const tracks=m.audio.map(r=>{if(!r||typeof r.id!=='string'||ids.has(r.id)||typeof r.name!=='string'||!['music','sound'].includes(r.kind)||!files.has(r.file))throw Error('Повреждён список аудиофайлов.');ids.add(r.id);const {file,mime,...metadata}=r;return {...metadata,blob:files.get(file).slice(0,undefined,typeof mime==='string'?mime:'')};});return {campaigns:m.campaigns,tracks,settings:m.settings};}
async function restoreAudio(value){const db=await openDB();try{return await new Promise((resolve,reject)=>{let added=0;const t=db.transaction('tracks','readwrite'),s=t.objectStore('tracks');for(const track of value.tracks){const r=s.get(track.id);r.onsuccess=()=>{if(!r.result){s.add(track);added++;}};}t.oncomplete=()=>resolve(added);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Не удалось сохранить аудио.'));});}finally{db.close();}}
root.FullBackup={pack,unpack,create,read,restoreAudio};if(typeof module!=='undefined')module.exports=root.FullBackup;
})(typeof window==='undefined'?globalThis:window);
