(function(root){'use strict';
const spells=[['identify','Опознание',1],['ray of sickness','Луч болезни',1],['hold person','Удержание личности',2],['locate object','Поиск предмета',2],['bestow curse','Проклятие',3],['counterspell','Контрзаклинание',3],['lightning bolt','Молния',3],['phantasmal killer','Воображаемый убийца',4],['polymorph','Превращение',4],['contact other plane','Связь с иным миром',5],['scrying','Наблюдение',5],['eyebite','Укус взгляда',6]];
const capacities=[4,3,3,3,2,1];
function isHag(c){return !!c.isMonster&&/(?:\b(?:green|night|sea|annis|bheur) hag\b|карга)/i.test(c.name||'');}
function members(all,c){return c.covenGroup?all.filter(a=>a.covenGroup===c.covenGroup).sort((a,b)=>Number(a.id)-Number(b.id)):[];}
function active(all,c){const group=members(all,c);return group.length===3&&group.every(a=>isHag(a)&&a.covenActive&&Number(a.currentHp)>0);}
function sync(all){const seen=new Set();for(const c of all){c.spellSlots||={};for(const k of Object.keys(c.spellSlots))if(k.startsWith('coven-'))delete c.spellSlots[k];}for(const c of all){if(!c.covenGroup||seen.has(c.covenGroup))continue;seen.add(c.covenGroup);const group=members(all,c),pool=group.find(a=>a.covenSlots)?.covenSlots||{};for(let i=1;i<=6;i++){pool[i]||={max:capacities[i-1],used:0};pool[i].max=capacities[i-1];pool[i].used=Math.max(0,Math.min(pool[i].max,Number(pool[i].used)||0));}for(const a of group){a.covenSlots=pool;if(active(all,a))for(let i=1;i<=6;i++)a.spellSlots['coven-'+i]=pool[i];}}}
function configure(all,ids,enabled=true){if(new Set(ids.map(String)).size!==3)throw Error('Выберите ровно трёх карг.');const selected=ids.map(id=>all.find(c=>String(c.id)===String(id)));if(selected.some(c=>!c||!isHag(c)))throw Error('Участниками должны быть карги.');const existing=selected[0].covenGroup;const same=existing&&selected.every(c=>c.covenGroup===existing)&&members(all,selected[0]).length===3;const pool=same?selected[0].covenSlots:{};for(const c of selected)if(c.covenGroup&&!same)throw Error('Карга уже в другом шабаше. Сначала расформируйте его.');const id=same?existing:'coven-'+Date.now()+'-'+Math.random().toString(36).slice(2);for(const c of selected){c.covenGroup=id;c.covenActive=enabled;c.covenSlots=pool;}sync(all);}
function dissolve(all,c){for(const a of members(all,c)){delete a.covenGroup;delete a.covenActive;delete a.covenSlots;}sync(all);}
function casting(c){const mod=Number(c.stats?.int?.mod??Math.floor((Number(c.stats?.int?.score||10)-10)/2));return {dc:12+mod,attack:4+mod};}
root.HagCoven={spells,isHag,members,active,sync,configure,dissolve,casting};if(typeof module!=='undefined'&&module.exports)module.exports=root.HagCoven;
})(typeof globalThis!=='undefined'?globalThis:window);
