(function(root){
'use strict';
const abilities={str:'Сила',dex:'Ловкость',con:'Телосложение',int:'Интеллект',wis:'Мудрость',cha:'Харизма'};
const skills=[['Акробатика','dex'],['Анализ','int'],['Атлетика','str'],['Внимательность','wis'],['Выживание','wis'],['Выступление','cha'],['Запугивание','cha'],['История','int'],['Ловкость рук','dex'],['Магия','int'],['Медицина','wis'],['Обман','cha'],['Природа','int'],['Проницательность','wis'],['Религия','int'],['Скрытность','dex'],['Убеждение','cha'],['Уход за животными','wis']];
const sections={features:'Особенности',actions:'Действия',bonusActions:'Бонусные действия',reactions:'Реакции',legendaryActions:'Легендарные действия',lairActions:'Действия логова'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sign=n=>n>=0?'+'+n:String(n);
function build(d){
 const num=(k,v=0)=>{const n=Number(d[k]);return Number.isFinite(n)?n:v;};
 const stats=Object.fromEntries(Object.keys(abilities).map(k=>{const score=Math.max(1,Math.min(30,num(k,10)));return[k,{score,mod:Math.floor((score-10)/2)}];}));
 const prof=Math.max(0,num('prof',2)),skillRanks=d.skillRanks||{};
 const result={name:String(d.name||'').trim(),ac:Math.max(1,num('ac',14)),hpFormula:String(d.hpFormula||'').trim().replace(/д/gi,'d'),hp:String(d.hpFormula||''),initBonus:d.init===''?stats.dex.mod:num('init'),speed:String(d.speed||30)+' футов',type:d.type||'Монстр',size:d.size||'medium',alignment:d.alignment||'Без мировоззрения',cr:Math.max(0,num('cr')),source:'Свои монстры',image:String(d.image||'').trim(),stats,profBonus:prof,saves:(d.saves||[]).map(k=>abilities[k]+' '+sign(stats[k].mod+prof)).join(', '),skills:skills.filter(([n])=>skillRanks[n]>0).map(([n,k])=>n+' '+sign(stats[k].mod+prof*skillRanks[n])).join(', '),senses:String(d.senses||''),languages:String(d.languages||''),damage_resistances:String(d.resist||''),damage_immunities:String(d.immun||''),condition_immunities:String(d.conditions||''),spells:[...(d.spells||[])],spellSlots:{},_customMonster:true,_builderDraft:structuredClone(d)};
 for(const k of Object.keys(sections))result[k]=(d.entries?.[k]||[]).filter(e=>e.name.trim()||e.description.trim()).map(e=>({name:e.name.trim()||sections[k],description:'<p>'+esc(e.description).replace(/\n/g,'<br>')+'</p>'}));
 const magic=d.magicAbility||'int';result.spellSaveDC=8+prof+stats[magic].mod;result.spellAttack=prof+stats[magic].mod;
 const slotRows=[];for(let i=1;i<=9;i++){const max=Math.max(0,Math.floor(Number(d.slots?.[i])||0));if(max){result.spellSlots[i]={max,used:0};slotRows.push(`${i}-й круг (${max} ячеек)`);}}
 if(result.spells.length||slotRows.length)result.features.unshift({name:'Использование заклинаний',description:`<p>Базовая характеристика: ${abilities[magic]}. СЛ спасброска ${result.spellSaveDC}; атака заклинаниями ${sign(result.spellAttack)}.</p>`+slotRows.map(r=>'<p>'+r+'</p>').join('')});
 return result;
}
function open({spells,onSave,existing=null}){
 const modal=document.getElementById('customModal');let draft=existing?structuredClone(existing._builderDraft):{name:'',ac:14,hpFormula:'6d8+12',init:'',speed:30,prof:2,cr:0,type:'Монстр',size:'medium',magicAbility:'int',entries:{},spells:[],slots:{},skillRanks:{},saves:[]};
 const field=(key,label,value='',type='text')=>`<label>${label}<input name="${key}" type="${type}" value="${esc(draft[key]??value)}" ${type==='number'?'step="any"':''}></label>`;
 const select=(key,label,options)=>`<label>${label}<select name="${key}">${options.map(([v,n])=>`<option value="${esc(v)}" ${draft[key]===v?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`;
 modal.innerHTML=`<form class="modal-content monster-builder" id="monsterBuilderForm"><div class="builder-heading"><div><small>СВОЙ БЕСТИАРИЙ</small><h2>${existing?'Редактирование':'Создание'} монстра</h2></div><button type="button" class="builder-close" aria-label="Закрыть">×</button></div><nav class="builder-tabs" aria-label="Разделы монстра">${['Основное','Характеристики','Действия','Заклинания','Защита'].map((n,i)=>`<button type="button" data-tab="${i}" class="${i===0?'selected':''}">${n}</button>`).join('')}</nav>
 <section data-page="0"><div class="builder-grid">${field('name','Название')}${field('image','Ссылка на изображение')}${field('ac','Класс защиты',14,'number')}${field('hpFormula','Формула ХП','6d8+12')}${field('speed','Скорость, футы',30,'number')}${field('init','Бонус инициативы · пусто = ЛОВ','','number')}${field('cr','Опасность (CR)',0,'number')}${field('prof','Бонус мастерства',2,'number')}${select('type','Вид',['Гуманоид','Зверь','Дракон','Нежить','Исчадие','Монстр','Конструкт','Фея','Элементаль','Великан','Небожитель','Растение','Слизь','Аберрация'].map(x=>[x,x]))}${select('size','Размер',[['tiny','Крошечный'],['small','Маленький'],['medium','Средний'],['large','Большой'],['huge','Огромный'],['gargantuan','Громадный']])}${field('alignment','Мировоззрение','Без мировоззрения')}${field('languages','Языки')}</div></section>
 <section data-page="1" hidden><div class="builder-abilities">${Object.entries(abilities).map(([k,n])=>field(k,n,10,'number')).join('')}</div><h3>Спасброски · владение</h3><div class="builder-checks">${Object.entries(abilities).map(([k,n])=>`<label><input type="checkbox" name="save-${k}" ${(draft.saves||[]).includes(k)?'checked':''}>${n}</label>`).join('')}</div><h3>Навыки</h3><div class="builder-skills">${skills.map(([n,k],i)=>`<label>${n}<select data-skill="${i}"><option value="0">Без владения</option><option value="1" ${draft.skillRanks?.[n]===1?'selected':''}>Владение</option><option value="2" ${draft.skillRanks?.[n]===2?'selected':''}>Компетентность</option></select></label>`).join('')}</div><p class="builder-hint">Бонусы рассчитываются из характеристик и бонуса мастерства.</p></section>
 <section data-page="2" hidden><div class="builder-grid"><label>Раздел<select id="builderEntrySection">${Object.entries(sections).map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label><button type="button" id="builderAddEntry">+ Добавить способность</button></div><div id="builderEntries"></div></section>
 <section data-page="3" hidden><div class="builder-grid">${select('magicAbility','Характеристика заклинаний',Object.entries(abilities))}<div class="builder-magic" id="builderMagicSummary"></div></div><h3>Ячейки заклинаний</h3><div class="builder-slots">${Array.from({length:9},(_,i)=>`<label>${i+1} круг<input type="number" min="0" max="99" name="slot-${i+1}" value="${draft.slots?.[i+1]||0}"></label>`).join('')}</div><h3>Изученные заклинания</h3><div id="builderSelectedSpells"></div><input type="search" id="builderSpellSearch" placeholder="Поиск заклинания по названию" aria-label="Поиск заклинания для монстра"><div id="builderSpellResults"></div><p class="builder-hint">Выбранные заклинания появятся в подробной информации; ячейки — на карточке боя.</p></section>
 <section data-page="4" hidden><div class="builder-grid">${field('senses','Чувства и зрение','тёмное зрение 60 футов')}${field('resist','Сопротивления урону')}${field('immun','Иммунитеты к урону')}${field('conditions','Иммунитеты к состояниям')}</div></section>
 <footer class="builder-footer"><span id="builderStatus" role="status">Сохраняется в своём бестиарии в этом браузере</span><label class="builder-add-combat"><input type="checkbox" name="addToCombat" ${existing?'':'checked'}>Добавить в бой</label><button type="submit">${existing?'Сохранить':'Создать монстра'}</button></footer></form>`;
 modal.style.display='flex';const form=modal.querySelector('form');
 const collect=()=>{for(const input of form.querySelectorAll('input[name],select[name]')){if(input.name.startsWith('save-')||input.name.startsWith('slot-')||input.name==='addToCombat')continue;draft[input.name]=input.value;}draft.saves=Object.keys(abilities).filter(k=>form.elements['save-'+k].checked);draft.skillRanks=Object.fromEntries([...form.querySelectorAll('[data-skill]')].map(el=>[skills[Number(el.dataset.skill)][0],Number(el.value)]));draft.slots=Object.fromEntries(Array.from({length:9},(_,i)=>[i+1,Number(form.elements['slot-'+(i+1)].value)]));for(const row of form.querySelectorAll('[data-entry-section]')){const e=draft.entries[row.dataset.entrySection][Number(row.dataset.entryIndex)];e.name=row.querySelector('input').value;e.description=row.querySelector('textarea').value;}};
 const renderEntries=()=>{document.getElementById('builderEntries').innerHTML=Object.entries(sections).map(([k,n])=>{const entries=draft.entries[k]||[];return entries.length?`<h3>${n}</h3>`+entries.map((e,i)=>`<article class="builder-entry" data-entry-section="${k}" data-entry-index="${i}"><div><input placeholder="Название способности" aria-label="Название способности" value="${esc(e.name)}"><button type="button" data-remove-entry="${k}:${i}" aria-label="Удалить способность">×</button></div><textarea placeholder="Описание, атака, урон, спасбросок…" aria-label="Описание способности">${esc(e.description)}</textarea></article>`).join(''):'';}).join('')||'<p class="builder-hint">Добавьте особенности, атаки, реакции или легендарные действия.</p>';};
 const renderSelected=()=>{document.getElementById('builderSelectedSpells').innerHTML=draft.spells.map((n,i)=>`<button type="button" data-remove-spell="${i}">${esc(n.split(/\s+\/\s+/)[0])} ×</button>`).join('')||'<small class="builder-hint">Пока нет заклинаний</small>';};
 const search=()=>{const q=document.getElementById('builderSpellSearch').value.trim().toLowerCase();document.getElementById('builderSpellResults').innerHTML=q?spells.filter(s=>s.spellName.toLowerCase().includes(q)&&!draft.spells.includes(s.spellName)).slice(0,25).map(s=>`<button type="button" data-add-spell="${esc(s.spellName)}"><span>${esc(s.spellName.split(/\s+\/\s+/)[0])}</span><small>${s.level===0?'Заговор':s.level+' круг'} · +</small></button>`).join('')||'<small>Ничего не найдено</small>':'';};
 form.onclick=e=>{const tab=e.target.closest('[data-tab]');if(tab){for(const page of form.querySelectorAll('[data-page]'))page.hidden=page.dataset.page!==tab.dataset.tab;for(const btn of form.querySelectorAll('[data-tab]'))btn.classList.toggle('selected',btn===tab);}const del=e.target.closest('[data-remove-entry]');if(del){collect();const[k,i]=del.dataset.removeEntry.split(':');draft.entries[k].splice(Number(i),1);renderEntries();}const add=e.target.closest('[data-add-spell]');if(add){draft.spells.push(add.dataset.addSpell);renderSelected();search();}const remove=e.target.closest('[data-remove-spell]');if(remove){draft.spells.splice(Number(remove.dataset.removeSpell),1);renderSelected();search();}};
 form.querySelector('.builder-close').onclick=()=>modal.style.display='none';
 document.getElementById('builderAddEntry').onclick=()=>{collect();const k=document.getElementById('builderEntrySection').value;draft.entries[k]||=[];draft.entries[k].push({name:'',description:''});renderEntries();};
 document.getElementById('builderSpellSearch').oninput=search;
 form.oninput=()=>{collect();const m=build(draft);document.getElementById('builderMagicSummary').textContent=`СЛ ${m.spellSaveDC} · атака ${sign(m.spellAttack)}`;};
 form.onsubmit=e=>{e.preventDefault();collect();const status=document.getElementById('builderStatus');if(!draft.name.trim()){status.textContent='Укажите название монстра';return;}if(!/^[1-9]\d*(?:[dд][1-9]\d*)?(?:\s*\+\s*\d+)?$/i.test(draft.hpFormula.trim())){status.textContent='Формула ХП: например 6d8+12 или 45';return;}try{onSave(build(draft),form.elements.addToCombat.checked,existing);modal.style.display='none';}catch(error){status.textContent=error.message;}};
 renderEntries();renderSelected();form.oninput();
}
root.MonsterBuilder={open,build};if(typeof module!=='undefined')module.exports=root.MonsterBuilder;
})(typeof window==='undefined'?globalThis:window);
