(function(root){
'use strict';
const abilities={str:'Сила',dex:'Ловкость',con:'Телосложение',int:'Интеллект',wis:'Мудрость',cha:'Харизма'};
const skills=[['Акробатика','dex'],['Анализ','int'],['Атлетика','str'],['Внимательность','wis'],['Выживание','wis'],['Выступление','cha'],['Запугивание','cha'],['История','int'],['Ловкость рук','dex'],['Магия','int'],['Медицина','wis'],['Обман','cha'],['Природа','int'],['Проницательность','wis'],['Религия','int'],['Скрытность','dex'],['Убеждение','cha'],['Уход за животными','wis']];
const sections={features:'Особенности',actions:'Действия',bonusActions:'Бонусные действия',reactions:'Реакции',legendaryActions:'Легендарные действия',lairActions:'Действия логова',regionalEffects:'Региональные эффекты'};
const sectionKeys={bonusActions:'bonus_actions',legendaryActions:'legendary_actions',lairActions:'lair_actions',regionalEffects:'regional_effects'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sign=n=>n>=0?'+'+n:String(n);
function build(d){
 const num=(k,v=0)=>{const n=Number(d[k]);return Number.isFinite(n)?n:v;};
 const stats=Object.fromEntries(Object.keys(abilities).map(k=>{const score=Math.max(1,Math.min(30,num(k,10)));return[k,{score,mod:Math.floor((score-10)/2)}];}));
 const prof=Math.max(0,num('prof',2)),skillRanks=d.skillRanks||{};
 const result={name:String(d.name||'').trim(),ac:Math.max(1,num('ac',14)),hpFormula:String(d.hpFormula||'').trim().replace(/д/gi,'d'),hp:String(d.hpFormula||''),initBonus:d.init===''?stats.dex.mod:num('init'),speed:String(d.speed||30)+' футов',type:d.type||'Монстр',size:d.size||'medium',alignment:d.alignment||'Без мировоззрения',cr:Math.max(0,num('cr')),source:'Свои монстры',image:String(d.image||'').trim(),stats,profBonus:prof,saves:(d.saves||[]).map(k=>abilities[k]+' '+sign(stats[k].mod+prof)).join(', '),skills:skills.filter(([n])=>skillRanks[n]>0).map(([n,k])=>n+' '+sign(stats[k].mod+prof*skillRanks[n])).join(', '),senses:String(d.senses||''),languages:String(d.languages||''),damage_resistances:String(d.resist||''),damage_immunities:String(d.immun||''),condition_immunities:String(d.conditions||''),spells:[...(d.spells||[])],spellSlots:{},_customMonster:true,_builderDraft:structuredClone(d)};
 for(const k of Object.keys(sections))result[k]=(d.entries?.[k]||[]).filter(e=>e.name.trim()||e.description.trim()).map(e=>({name:e.name.trim()||sections[k],description:e.originalText===e.description?e.originalDescription:'<p>'+esc(e.description).replace(/\n/g,'<br>')+'</p>'}));
 for(const [key,field] of Object.entries(sectionKeys))result[field]=result[key];
 const magic=d.magicAbility||'int';result.spellSaveDC=8+prof+stats[magic].mod;result.spellAttack=prof+stats[magic].mod;
 const slotRows=[];for(let i=1;i<=9;i++){const max=Math.max(0,Math.floor(Number(d.slots?.[i])||0));if(max){result.spellSlots[i]={max,used:0};slotRows.push(`${i}-й круг (${max} ячеек)`);}}
 if((result.spells.length||slotRows.length)&&!result.features.some(e=>/^(?:использование заклинаний|заклинания|врожд[её]нное колдовство|spellcasting)/i.test(e.name)))result.features.unshift({name:'Использование заклинаний',description:`<p>Базовая характеристика: ${abilities[magic]}. СЛ спасброска ${result.spellSaveDC}; атака заклинаниями ${sign(result.spellAttack)}.</p>`+slotRows.map(r=>'<p>'+r+'</p>').join('')});
 return result;
}
function open({spells,onSave,existing=null}){
 const modal=document.getElementById('customModal');
 const plain=html=>{const el=document.createElement('div');el.innerHTML=String(html||'').replace(/<br\s*\/?\s*>|<\/p>/gi,'\n');return(el.textContent||'').trim();};
 const fromExisting=m=>{
   const d={name:m.name,ac:m.ac,hpFormula:m.hpFormula||m._hpFormula||'6d8+12',init:m.initBonus??'',speed:parseInt(m.speed)||30,prof:m.profBonus||2,cr:m.cr||0,type:({'humanoid':'Гуманоид','undead':'Нежить','fiend':'Исчадие','beast':'Зверь','dragon':'Дракон','construct':'Конструкт','fey':'Фея','elemental':'Элементаль','giant':'Великан','celestial':'Небожитель','plant':'Растение','ooze':'Слизь','aberration':'Аберрация','monstrosity':'Монстр'}[String(m.type).toLowerCase()]||m.type||'Монстр'),size:({'крошечный':'tiny','маленький':'small','средний':'medium','большой':'large','огромный':'huge','громадный':'gargantuan'}[String(m.size).toLowerCase()]||m.size||'medium'),alignment:m.alignment||'',image:m.image||'',senses:m.senses||'',languages:m.languages||'',resist:m.damage_resistances||'',immun:m.damage_immunities||'',conditions:m.condition_immunities||'',magicAbility:'int',entries:{},spells:[],slots:{},skillRanks:{},saves:[]};
   for(const k of Object.keys(abilities))d[k]=m.stats?.[k]?.score||10;
   for(const k of Object.keys(sections))d.entries[k]=(m[sectionKeys[k]||k]||m[k]||[]).map(e=>({name:e.name||'',description:plain(e._displayDescription??e.description),originalText:plain(e._displayDescription??e.description),originalDescription:e._displayDescription??e.description}));
   for(const k of Object.keys(abilities))if(String(m.saves||'').toLowerCase().includes(abilities[k].toLowerCase()))d.saves.push(k);
   for(const [n,k] of skills){const escaped=n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const match=String(m.skills||'').match(new RegExp(escaped+'\\s*([+-]\\d+)','i'));if(match){const bonus=Number(match[1])-Math.floor((d[k]-10)/2);d.skillRanks[n]=bonus>=d.prof*2?2:1;}}
   for(const ref of m.spells||[]){const spell=spells.find(s=>s.spellName===ref||s.id===ref||s._id===ref||s.uuid===ref);const name=spell?.spellName||(typeof ref==='string'?ref:ref.name);if(name&&!d.spells.includes(name))d.spells.push(name);}
   for(const e of [...(m.features||[]),...(m.actions||[])]){const text=plain(e._displayDescription??e.description);for(const match of text.matchAll(/(\d+)[‐‑–—-]?(?:й|го)?\s*(?:круг|уровень)\s*\((\d+)\s*ячей/gi))d.slots[match[1]]=Number(match[2]);}
   for(const [k,v] of Object.entries(m.spellSlots||{}))d.slots[k]=v.max;
   return d;
 };
 let draft=existing?structuredClone(existing._builderDraft||fromExisting(existing)):{name:'',ac:14,hpFormula:'6d8+12',init:'',speed:30,prof:2,cr:0,type:'Монстр',size:'medium',magicAbility:'int',entries:{},spells:[],slots:{},skillRanks:{},saves:[]};
 let initialDraft;
 let uploadedImage=draft.image?.startsWith('data:image/')?draft.image:null;
 const field=(key,label,value='',type='text')=>`<label>${label}<input name="${key}" type="${type}" value="${esc(draft[key]??value)}" ${type==='number'?'step="any"':''}></label>`;
 const select=(key,label,options)=>`<label>${label}<select name="${key}">${options.map(([v,n])=>`<option value="${esc(v)}" ${draft[key]===v?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`;
 modal.innerHTML=`<form class="modal-content monster-builder" id="monsterBuilderForm"><div class="builder-heading"><div><small>СВОЙ БЕСТИАРИЙ</small><h2>${existing?'Редактирование':'Создание'} монстра</h2></div><button type="button" class="builder-close" aria-label="Закрыть">×</button></div><nav class="builder-tabs" aria-label="Разделы монстра">${['Основное','Характеристики','Действия','Заклинания','Защита'].map((n,i)=>`<button type="button" data-tab="${i}" class="${i===0?'selected':''}">${n}</button>`).join('')}</nav>
 <section data-page="0"><div class="builder-grid">${field('name','Название')}${field('image','Прямая ссылка на изображение')}<div class="builder-image-upload"><label>Или загрузите свою картинку<input type="file" id="builderImageFile" accept="image/*"></label><img id="builderImagePreview" alt="Предпросмотр монстра" hidden><small id="builderImageStatus"></small></div>${field('ac','Класс защиты',14,'number')}${field('hpFormula','Формула ХП','6d8+12')}${field('speed','Скорость, футы',30,'number')}${field('init','Бонус инициативы · пусто = ЛОВ','','number')}${field('cr','Опасность (CR)',0,'number')}${field('prof','Бонус мастерства',2,'number')}${select('type','Вид',['Гуманоид','Зверь','Дракон','Нежить','Исчадие','Монстр','Конструкт','Фея','Элементаль','Великан','Небожитель','Растение','Слизь','Аберрация'].map(x=>[x,x]))}${select('size','Размер',[['tiny','Крошечный'],['small','Маленький'],['medium','Средний'],['large','Большой'],['huge','Огромный'],['gargantuan','Громадный']])}${field('alignment','Мировоззрение','Без мировоззрения')}${field('languages','Языки')}</div></section>
 <section data-page="1" hidden><div class="builder-abilities">${Object.entries(abilities).map(([k,n])=>field(k,n,10,'number')).join('')}</div><h3>Спасброски · владение</h3><div class="builder-checks">${Object.entries(abilities).map(([k,n])=>`<label><input type="checkbox" name="save-${k}" ${(draft.saves||[]).includes(k)?'checked':''}>${n}</label>`).join('')}</div><h3>Навыки</h3><div class="builder-skills">${skills.map(([n,k],i)=>`<label>${n}<select data-skill="${i}"><option value="0">Без владения</option><option value="1" ${draft.skillRanks?.[n]===1?'selected':''}>Владение</option><option value="2" ${draft.skillRanks?.[n]===2?'selected':''}>Компетентность</option></select></label>`).join('')}</div><p class="builder-hint">Бонусы рассчитываются из характеристик и бонуса мастерства.</p></section>
 <section data-page="2" hidden><div class="builder-grid"><label>Раздел<select id="builderEntrySection">${Object.entries(sections).map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label><button type="button" id="builderAddEntry">+ Добавить способность</button></div><div id="builderEntries"></div></section>
 <section data-page="3" hidden><div class="builder-grid">${select('magicAbility','Характеристика заклинаний',Object.entries(abilities))}<div class="builder-magic" id="builderMagicSummary"></div></div><h3>Ячейки заклинаний</h3><div class="builder-slots">${Array.from({length:9},(_,i)=>`<label>${i+1} круг<input type="number" min="0" max="99" name="slot-${i+1}" value="${draft.slots?.[i+1]||0}"></label>`).join('')}</div><h3>Изученные заклинания</h3><div id="builderSelectedSpells"></div><input type="search" id="builderSpellSearch" placeholder="Поиск заклинания по названию" aria-label="Поиск заклинания для монстра"><div id="builderSpellResults"></div><p class="builder-hint">Выбранные заклинания появятся в подробной информации; ячейки — на карточке боя.</p></section>
 <section data-page="4" hidden><div class="builder-grid">${field('senses','Чувства и зрение','тёмное зрение 60 футов')}${field('resist','Сопротивления урону')}${field('immun','Иммунитеты к урону')}${field('conditions','Иммунитеты к состояниям')}</div></section>
 <footer class="builder-footer"><span id="builderStatus" role="status">Сохраняется в своём бестиарии в этом браузере</span><label class="builder-add-combat"><input type="checkbox" name="addToCombat" ${existing?'':'checked'}>Добавить в бой</label><button type="submit">${existing?'Сохранить':'Создать монстра'}</button></footer></form>`;
 modal.style.display='flex';const form=modal.querySelector('form');
 const collect=()=>{for(const input of form.querySelectorAll('input[name],select[name]')){if(input.name.startsWith('save-')||input.name.startsWith('slot-')||input.name==='addToCombat')continue;draft[input.name]=input.name==='image'&&uploadedImage&&!input.value?uploadedImage:input.value;}draft.saves=Object.keys(abilities).filter(k=>form.elements['save-'+k].checked);draft.skillRanks=Object.fromEntries([...form.querySelectorAll('[data-skill]')].map(el=>[skills[Number(el.dataset.skill)][0],Number(el.value)]));draft.slots=Object.fromEntries(Array.from({length:9},(_,i)=>[i+1,Number(form.elements['slot-'+(i+1)].value)]));for(const row of form.querySelectorAll('[data-entry-section]')){const e=draft.entries[row.dataset.entrySection][Number(row.dataset.entryIndex)];e.name=row.querySelector('input').value;e.description=row.querySelector('textarea').value;}};
 const renderEntries=()=>{document.getElementById('builderEntries').innerHTML=Object.entries(sections).map(([k,n])=>{const entries=draft.entries[k]||[];return entries.length?`<h3>${n}</h3>`+entries.map((e,i)=>`<article class="builder-entry" data-entry-section="${k}" data-entry-index="${i}"><div><input placeholder="Название способности" aria-label="Название способности" value="${esc(e.name)}"><button type="button" data-remove-entry="${k}:${i}" aria-label="Удалить способность">×</button></div><textarea placeholder="Описание, атака, урон, спасбросок…" aria-label="Описание способности">${esc(e.description)}</textarea></article>`).join(''):'';}).join('')||'<p class="builder-hint">Добавьте особенности, атаки, реакции или легендарные действия.</p>';};
 const renderSelected=()=>{document.getElementById('builderSelectedSpells').innerHTML=draft.spells.map((n,i)=>`<button type="button" data-remove-spell="${i}">${esc(n.split(/\s+\/\s+/)[0])} ×</button>`).join('')||'<small class="builder-hint">Пока нет заклинаний</small>';};
 const search=()=>{const q=document.getElementById('builderSpellSearch').value.trim().toLowerCase();document.getElementById('builderSpellResults').innerHTML=q?spells.filter(s=>s.spellName.toLowerCase().includes(q)&&!draft.spells.includes(s.spellName)).slice(0,25).map(s=>`<button type="button" data-add-spell="${esc(s.spellName)}"><span>${esc(s.spellName.split(/\s+\/\s+/)[0])}</span><small>${s.level===0?'Заговор':s.level+' круг'} · +</small></button>`).join('')||'<small>Ничего не найдено</small>':'';};
 form.onclick=e=>{const tab=e.target.closest('[data-tab]');if(tab){for(const page of form.querySelectorAll('[data-page]'))page.hidden=page.dataset.page!==tab.dataset.tab;for(const btn of form.querySelectorAll('[data-tab]'))btn.classList.toggle('selected',btn===tab);}const del=e.target.closest('[data-remove-entry]');if(del){collect();const[k,i]=del.dataset.removeEntry.split(':');draft.entries[k].splice(Number(i),1);renderEntries();}const add=e.target.closest('[data-add-spell]');if(add){draft.spells.push(add.dataset.addSpell);renderSelected();search();}const remove=e.target.closest('[data-remove-spell]');if(remove){draft.spells.splice(Number(remove.dataset.removeSpell),1);renderSelected();search();}};
 form.querySelector('.builder-close').onclick=()=>modal.style.display='none';
 document.getElementById('builderAddEntry').onclick=()=>{collect();const k=document.getElementById('builderEntrySection').value;draft.entries[k]||=[];draft.entries[k].push({name:'',description:''});renderEntries();};
 document.getElementById('builderSpellSearch').oninput=search;
 form.oninput=()=>{collect();const m=build(draft);document.getElementById('builderMagicSummary').textContent=`СЛ ${m.spellSaveDC} · атака ${sign(m.spellAttack)}`;};
 form.onsubmit=e=>{e.preventDefault();collect();const status=document.getElementById('builderStatus');if(!draft.name.trim()){status.textContent='Укажите название монстра';return;}if(!/^[1-9]\d*(?:[dд][1-9]\d*)?(?:\s*[+-]\s*\d+)?$/i.test(draft.hpFormula.trim())){status.textContent='Формула ХП: например 6d8+12 или 45';return;}try{const result=build(draft);if(existing&&initialDraft){const same=keys=>keys.every(k=>JSON.stringify(draft[k])===JSON.stringify(initialDraft[k]));const preserve=(keys,fields)=>{if(same(keys))for(const k of fields)if(existing[k]!==undefined)result[k]=structuredClone(existing[k]);};preserve(['speed'],['speed']);preserve(['saves','str','dex','con','int','wis','cha','prof'],['saves']);preserve(['skillRanks','str','dex','con','int','wis','cha','prof'],['skills']);preserve(['magicAbility','str','dex','con','int','wis','cha','prof'],['spellSaveDC','spellAttack']);}onSave(result,form.elements.addToCombat.checked,existing);modal.style.display='none';}catch(error){status.textContent=error.message;}};
 const imageInput=form.elements.image,preview=document.getElementById('builderImagePreview'),imageStatus=document.getElementById('builderImageStatus');
 const previewImage=src=>{preview.hidden=!src;if(src)preview.src=src;};
 preview.onerror=()=>{preview.hidden=true;imageStatus.textContent='Картинка не загрузилась. Нужна прямая ссылка на файл или загрузка с компьютера.';};
 preview.onload=()=>{imageStatus.textContent='Изображение готово';};
 if(uploadedImage){imageInput.value='';imageInput.placeholder='Картинка загружена';}
 previewImage(draft.image);
 imageInput.addEventListener('input',()=>{uploadedImage=null;previewImage(imageInput.value.trim());});
 document.getElementById('builderImageFile').onchange=e=>{
   const file=e.target.files[0];if(!file)return;
   if(!file.type.startsWith('image/')||file.size>10*1024*1024){imageStatus.textContent='Выберите изображение до 10 МБ';return;}
   const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,720/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);uploadedImage=canvas.toDataURL('image/webp',.82);imageInput.value='';imageInput.placeholder='Картинка загружена';draft.image=uploadedImage;previewImage(uploadedImage);};img.onerror=()=>imageStatus.textContent='Не удалось прочитать изображение';img.src=reader.result;};reader.readAsDataURL(file);
 };
 renderEntries();renderSelected();form.oninput();initialDraft=structuredClone(draft);
}
root.MonsterBuilder={open,build};if(typeof module!=='undefined')module.exports=root.MonsterBuilder;
})(typeof window==='undefined'?globalThis:window);
