const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),B=require('../bestiary');
const raw=JSON.parse(fs.readFileSync('monsters_full_export.json')),sources=JSON.parse(fs.readFileSync('bestiary-structure.json'));
function monster(en){const m=structuredClone(raw.find(m=>m.name.endsWith('/ '+en)));assert(B.applyStructure(m,sources.find(s=>s.name===m.name)));return B.organize(m);}
const mother=monster('Drow Matron Mother');assert.equal(mother.features.length,3);assert.equal(mother.actions.length,5);assert.equal(mother.bonus_actions.length,2);assert.equal(mother.legendary_actions.length,4);assert.equal(mother.lair_actions.length,3);assert.equal(mother.legendary_actions.find(x=>x.name==='Сотворение заклинания').cost,2);assert(mother.actions.find(x=>x.name==='Заклинания').description.includes('Харизму'));
const pit=monster('Pit Fiend');assert(pit.actions.some(x=>x.name==='Призыв дьявола'));assert(!pit.features.some(x=>x.name==='Призыв дьявола'));
const h=fs.readFileSync('index.html','utf8'),allSpellsList=JSON.parse(fs.readFileSync('spells_full.json')).map(s=>({...s,spellName:s.name}));const ctx={FoundryData:{aliases:JSON.parse(fs.readFileSync("spell-aliases.json"))},Bestiary:B,allSpellsList,highlightSpellsInText:x=>B.renderText(x)};vm.createContext(ctx);vm.runInContext(h.slice(h.indexOf('    function findSpellByName'),h.indexOf('function resolveUuid')),ctx);vm.runInContext(h.slice(h.indexOf('    function renderSpellcasting'),h.indexOf('    function showSpellDetail')),ctx);
const rows=ctx.renderSpellcasting(pit.features.find(x=>/заклинания/i.test(x.name)).description);assert.equal((rows.match(/class="spellcasting-row"/g)||[]).length,2);assert(rows.includes('3/день каждое'));
const necro=raw.find(m=>m.name.endsWith('/ Necromancer'));const nc=ctx.renderSpellcasting(necro.features.find(x=>x.name==='Заклинания').description);assert(nc.includes('Слепота/Глухота'));assert(nc.includes('spellcasting-note'));assert(!nc.includes('>Слепота</span>'));
const text=B.renderText('Призывает Глабрезу или Йоклол.',{creatureRefs:['glabrezu'],findMonster:(_,name)=>name==='glabrezu'?{name:'Глабрезу / Glabrezu'}:null,monsterLink:(m,label)=>'<button data-monster="'+m.name+'">'+label+'</button>'});assert(text.includes('<button data-monster="Глабрезу / Glabrezu">Глабрезу</button>'));assert(!text.includes('>Йоклол</button>'));
assert.equal(B.clean('cold, fire, poisoned, darkvision 120 ft.'),'холод, огонь, отравленный, Тёмное зрение 120 фт.');
const bad=structuredClone(raw.find(m=>m.name.endsWith('/ Drow Matron Mother')));bad.stats.str.score++;assert(!B.applyStructure(bad,sources.find(s=>s.name===bad.name)));
console.log('PASS source-driven sections, shared action names, summon links, daily rows, compound spell names, footnote and mechanical enum translations');

const embedded=ctx.renderSpellcasting('Неограниченно:@ActorEmbeddedItem[actor][a]{Пляшущие огоньки}@ActorEmbeddedItem[actor][b]{Тьма}\n1/день каждое: @ActorEmbeddedItem[actor][c]{Левитация} (только на себя)');assert(!embedded.includes('@ActorEmbeddedItem'));assert.equal((embedded.match(/class="spell-link"/g)||[]).length,3);assert(embedded.includes('только на себя'));
const plainLevels=ctx.renderSpellcasting('Заговоры: Магическая рука\n1 круг (4 ячейки): Щит\n2 круг (3 ячейки): Паутина');assert.equal((plainLevels.match(/class="spellcasting-row"/g)||[]).length,3);
const joined=ctx.renderSpellcasting('Неограниченно: НевидимостьПаралич гуманоидаМагический доспехПриворот гуманоида');assert.equal((joined.match(/class="spell-link"/g)||[]).length,4);assert(joined.indexOf('data-level="1"')<joined.indexOf('data-level="2"'));
assert(ctx.findSpellByName('Сопротивление').spellName.endsWith('/ Resistance'));assert(ctx.findSpellByName('Указание').spellName.endsWith('/ Guidance'));
