const assert=require('node:assert/strict');
const E=require('../lss-engine');const H=require('../hero-card');
const d={stats:Object.fromEntries(Object.entries({str:8,dex:15,con:14,int:15,wis:10,cha:6}).map(([k,score])=>[k,{score}])),info:{level:2},proficiency:2,vitality:{ac:{value:'10+[DEX]'},'hp-max':{value:10}},skills:{arcana:{baseStat:'int'}},spellsInfo:{base:{code:'int'}},bonuses:[...['str','dex','int','cha'].map((k,i)=>({target:`stat.${k}.score`,mode:'add',value:[2,1,1,2][i]})),{target:'hp.max',expr:'[CON]*[LVL]'},{target:'speed.walk',mode:'set',value:30},{target:'prof.save.int',mode:'upgrade',value:1},{target:'prof.skill.arcana',mode:'upgrade',value:1},{target:'spellSlot.1',mode:'set',value:3},{target:'spellSlot.1',value:-1}]};
const r=E.resolve(d);assert.equal(r.stats.str.score,10);assert.equal(r.stats.dex.score,16);assert.equal(r.stats.int.score,16);assert.equal(r.stats.cha.score,8);assert.equal(r.vitality.ac.value,13);assert.equal(r.vitality['hp-max'].value,14);assert.equal(r.vitality.speed.value,30);assert.equal(r.saves.int.isProf,true);assert.equal(r.skills.arcana.isProf,1);assert.equal(r.spells['slots-1'].value,2);assert.equal(r._trackerSpellAttack,5);assert.equal(r._trackerSpellDc,13);assert.deepEqual(E.resolve(r),r);assert.equal(d.stats.str.score,8);
const h=H.ensure({heroData:r,stats:structuredClone(r.stats),ac:13,maxHp:14,initBonus:3});h.stats.dex.score=18;H.recalculate(h);assert.equal(h.ac,14);h.heroControls.shield=true;H.recalculate(h);assert.equal(h.ac,16);assert.match(H.panel(h, x=>String(x||"")),/hero-skills-grid/);
assert.doesNotThrow(()=>E.resolve({...d,vitality:{ac:{value:'10+[UNKNOWN]'}}}));
assert.throws(()=>E.expression('globalThis.process.exit()'));assert.throws(()=>E.expression('[UNKNOWN]'));assert.throws(()=>E.expression('1/0'));assert.equal(E.expression('max(10, 8+3)*2'),22);
console.log('PASS: LSS bonuses, formulas, proficiency, slots, immutable import, dynamic AC and safe expression parser');

for(const value of ['int','Интеллект','Intelligence']){const data={...d,stats:{...d.stats,int:{score:16}},bonuses:[],spellsInfo:{base:{value},mod:{value:''},save:{value:''}}};const r=E.resolve(data);assert.equal(r._trackerSpellAttack,5);assert.equal(r._trackerSpellDc,13);}

// Migrating older imported heroes must calculate modifiers before storing extras.
const legacy=H.ensure({heroData:structuredClone(d),stats:structuredClone(d.stats),ac:12,initBonus:2,proficiency:2});assert.equal(legacy.spellAttack,5);assert.equal(legacy.spellSaveDC,13);
const saved={heroSource:structuredClone(d),heroData:structuredClone(r),stats:structuredClone(r.stats),ac:13,proficiency:2,initBonus:3,spellAttack:8,spellSaveDC:16,heroControls:{baseAc:13,shield:false,items:[],proficiency:2,saveBonus:0,spellAbility:'int',spellAttackExtra:3,spellDcExtra:3,initiativeExtra:0,weapons:[]}};globalThis.LssEngine=E;H.ensure(saved);assert.equal(saved.spellAttack,5);assert.equal(saved.spellSaveDC,13);saved.stats.int.score=18;H.recalculate(saved);assert.equal(saved.spellAttack,6);assert.equal(saved.spellSaveDC,14);

const noSource=structuredClone(saved);delete noSource.heroSource;noSource._spellImportVersion=2;noSource.stats.int.score=16;noSource.spellAttack=8;noSource.spellSaveDC=16;noSource.heroControls.spellAttackExtra=3;noSource.heroControls.spellDcExtra=3;H.ensure(noSource);assert.equal(noSource.spellAttack,5);assert.equal(noSource.spellSaveDC,13);assert.equal(noSource._spellImportVersion,3);H.ensure(noSource);assert.equal(noSource.spellAttack,5);
