const fs=require('fs'),zlib=require('zlib'),assert=require('assert/strict'),M=require('../monster-mechanics'),F=require('../foundry-data'),B=require('../bestiary');
const manifest=JSON.parse(fs.readFileSync('foundry-data.json'));const data=JSON.parse(zlib.gunzipSync(Buffer.from(manifest.files.map(f=>fs.readFileSync(f,'utf8')).join(''),'base64')));const counts=JSON.parse(fs.readFileSync('foundry-resources.json'));
const get=name=>{const raw=data.monsters.find(m=>m.name.endsWith('/ '+name));return B.organize(F.applyMonster({}, {...raw,legendaryResistanceCount:counts[raw.name]||0}));};
assert.deepEqual(M.casting(get('Strahd von Zarovich')).map(m=>[m.dc,m.attack]),[[18,10]]);assert.deepEqual(M.casting(get('Archmage')).map(m=>[m.dc,m.attack]),[[17,9]]);assert.equal(M.casting(get('Vecna the Archlich'))[0].dc,22);
for(const wording of ['СЛ испытания от заклинания 18','СЛ испытаний против заклинаний 18','СЛ спасброска 18','spell save DC 18','СЛ 18'])assert.equal(M.casting({features:[{name:'Заклинания',description:wording}]})[0].dc,18);
assert.equal(M.text({value:[{text:'огонь'},'холод']}),'огонь, холод');assert(!M.text(get('Archmage').damage_resistances).includes('object'));assert(M.text(get('Archmage').damage_resistances).includes('урон от заклинаний'));
const c={};M.ensure(c,get('Strahd von Zarovich'),1);assert.equal(c.legendaryResources.actions.max,3);assert(M.spend(c,'actions',2));assert(!M.spend(c,'actions',2));assert(M.spend(c,'resistance'));M.ensure(c,get('Strahd von Zarovich'),2);assert.equal(c.legendaryResources.actions.used,0);assert.equal(c.legendaryResources.resistance.used,1);const v={};M.ensure(v,get('Vecna the Archlich'),1);assert.equal(v.legendaryResources.resistance.max,5);assert(!v.legendaryResources.actions);
for(const m of data.monsters){const modes=M.casting(B.organize(F.applyMonster({},m)));for(const mode of modes){if(mode.dc!==null)assert(mode.dc>0&&mode.dc<50,m.name);if(mode.attack!==null)assert(Number.isFinite(mode.attack),m.name);}}
console.log('PASS Strahd18/+10, Archmage17/+9, Vecna22; all 3396 caster records; structured text and legendary limits/spending/round persistence');
